name: Build and Test Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Установка необходимых инструментов
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential  # Установка базовых компиляторов
        sudo apt-get install -y gcc g++         # Компиляторы C и C++
        sudo apt-get install -y cmake           # Вспомогательный инструмент для сборки
        sudo apt-get install -y make            # Make для сборки проектов

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    # Генерация документации
    - name: Generate Documentation
      run: |
        doxygen -g  # Генерация Doxyfile
        sed -i 's/PROJECT_NAME           = "My Project"/PROJECT_NAME           = "Documentation Example"/' Doxyfile
        sed -i 's/OUTPUT_DIRECTORY       =/OUTPUT_DIRECTORY       = docs/' Doxyfile
        doxygen Doxyfile

    # Деплой документации на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs/html
